### PR TITLE
fix: Escape json references

### LINKED ISSUE #4648: Ensure XSS sanitisation/validation for JSON previews
Make sure XSS is prevented in:

1.	JSON References Feature
2.	Comparison Functions
3.	Identities Summary Page

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

JSON references JSON was not html escaped, this meant that setting a remote config value of `<div>test</div>` would render as markup when previewing JSON.

## How did you test this code?

image

### CODE REVIEW

File: frontend/web/components/JSONReference.tsx [hunk 1]
```diff
@@ -153,7 +153,7 @@ const JSONReference: FC<JSONReferenceType> = ({
               </Button>
             </Row>
             <div className='hljs-container'>
-              <Highlight forceExpanded preventEscape className={'json p-0'}>
```
Comment (khvn26) [inline frontend/web/components/JSONReference.tsx:156]: Just out of curiosity, why was `preventEscape` set in the first place?

**Review by khvn26 — APPROVED** [review]

File: frontend/web/components/JSONReference.tsx (hunk 1 above)
Comment (kyle-ssg) [reply frontend/web/components/JSONReference.tsx:156]: To be honest I'm not sure, I couldn't think of a good reason since in this case we are just showing JSON.
