### PR TITLE
fix: Dashboard alias not updating in safari

### LINKED ISSUE #5253: Can't save aliases on Safari
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [x] SaaS at flagsmith.com
- [ ] Some other way (add details in description below)

### Describe the bug

Pressing Enter to save an alias doesn't work, only on Safari:

https://github.com/user-attachments/assets/03ad6d5d-5ec6-454e-b171-1a062fbb9437

### Steps To Reproduce

See video above.

### Expected behavior

Aliases are saved correctly when pressing Enter after editing.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by Zaimwa9**
Thanks for submitting a PR! Please check the boxes below:

- [ ] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes
- Changed implementation from content-editable (not safari-compatible as of) to input component using ghost span to handle width
- Fixed locally crashing error ` Failed to execute 'setStart' on 'Range': parameter 1 is not of type 'Node'.` preventing from removing alias
- Fixed split test icon color
- Added max-length 100 on input (to avoid 400 from API)

## How did you test this code?
- Go to Environments -> Identities -> X User
- Update alias in safari and other browsers

_Please describe._
https://www.loom.com/share/c933e8a20dfe417f841f4e2da44991fb

### CODE REVIEW

File: frontend/web/components/EditIdentity.tsx [hunk 1]
```diff
@@ -73,48 +45,27 @@ const EditIdentity: FC<EditIdentityType> = ({ data, environmentId }) => {
...
-      selection?.addRange(newRange)
-    }
+  const handleInput = (e: React.ChangeEvent<HTMLInputElement>) => {
+    const newValue = e.target.value.toLowerCase()
+    setAlias(newValue.replace(/\n/g, ' ').trim())
   }
 
   return (
     <>
-      <span
```
Comment (Zaimwa9) [inline frontend/web/components/EditIdentity.tsx:100]: I understood the span implementation was to deal with width. Switched to input for simplicity and easier maintainability (and compabilities cross-browser) while dealing with the width.
Let me know if there was another reason and I'll work on the compatibility

**Review by kyle-ssg — APPROVED** [review]
