### PR TITLE
fix: Hide Sensitive Data switch

### LINKED ISSUE #4196: The 'Hide Sensitive Data' switch isn't working
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [X] Some other way (add details in description below)

### Describe the bug

Try enabling the 'hide sensitive data' switch but this never changes

### Steps To Reproduce

1. Go to environment settings
2. Try enabling the 'hide sensitive data' switch.
3. See the error (the switch never changes)

### Expected behavior

When enabling the 'hide sensitive data' switch, the option hide sensitive data in the environment should be true.

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by novakzaballa**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

- The 'Hide Sensitive Data' switch now enables and disables correctly.

## How did you test this code?

1. Go to environment settings
2. Try enabling the 'hide sensitive data' switch.

### CODE REVIEW

File: frontend/web/components/pages/EnvironmentSettingsPage.js [hunk 1]
```diff
@@ -224,15 +223,18 @@ const EnvironmentSettingsPage = class extends Component {
...
+  confirmToggle = (title, environmentProperty, environmentPropertyValue) => {
     openModal(
       title,
       <ConfirmToggleEnvFeature
-        description={`${description} Are you sure that you want to change this value?`}
-        feature={feature}
-        featureValue={this.state[feature]}
-        onToggleChange={(value) => {
-          this.setState({ [feature]: value }, this.saveEnv)
+        description={'Are you sure that you want to change this value?'}
```
Comment (kyle-ssg) [inline frontend/web/components/pages/EnvironmentSettingsPage.js:236]: This should ideally explain what the change will do

Comment (novakzaballa) [reply frontend/web/components/pages/EnvironmentSettingsPage.js:236]: This is how it looks now:

Screenshot 2024-06-20 at 9 20 52 AM


VS Before:

Screenshot 2024-06-20 at 9 27 45 AM

Comment (kyle-ssg) [reply frontend/web/components/pages/EnvironmentSettingsPage.js:236]: Should be in human readable form not snake case.. Also, what does this do? The title is also longer than the description, does not look right at all.

Title : confirm environment setting
Description : this will do xyz, are you sure?

Comment (novakzaballa) [reply frontend/web/components/pages/EnvironmentSettingsPage.js:236]: Screenshot 2024-06-25 at 11 56 16 AM

@kyle-ssg  This is the new version

**Review by kyle-ssg — APPROVED** [review]
