### PR TITLE
fix: Add Flagsmith signature header when testing webhook.

### LINKED ISSUE #2786: Include `x-flagsmith-signature` header when webhook is triggered by test webhook widget
Include `x-flagsmith-signature` header when webhook is triggered by test webhook widget

**To Reproduce**

1. Click on Create webhook and url and secret 
2. Click on test webhook
3. Observe: no  `x-flagsmith-signature` header is sent 

It should include ` x-flagsmith-signature` header

### PR DESCRIPTION
**Pull request by shubham-padia**
Fixes #2786.

Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have added information to `docs/` if required so people know about the feature!
No need to add info to the docs
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

We are trying to create the same signature as the webhook in the python code. This commit assumes that the python code will use the same approach to create signature for long term.

We are relying on notes here to make sure that both frontend and backend are implementing the same signature function, which is not the perfect approach. An alternative would be a backend endpoint to test the webhook so that the implementation always remains the same, but not sure if its overkill at this point or not. Note to maintainers: Please let me know what you think about both the approaches and what makes sense in this case since you might know best how the users might use this feature and how often the sign function might change. 

I'm also modifying the string on the frontend to be the exact same as the json.dumps output on the python side, so that the sign value is the same on both side. 

## How did you test this code?

- Created a webhook on the project settings, set the secret to `test123` and a dead example URL and noted down the header value: `X-Flagsmith-Signature: 1907ef6a4c7a3e0010504757728d8dbbf3980247e3e2c5835757b80e9fd1f085`
- 
Screenshot 2024-03-26 at 12 01 27 AM

- You can check that the replit [here](https://replit.com/@ShubhamPadia/test-hmac?v=1#main.py) will give the same signature. I also generated it in `test_unit_webhooks.py` by modifying the code to use the same example as frontend just to make sure there is no different when using the replit, but didn't commit the code since the current test is sufficient enough. 
Screenshot 2024-03-26 at 12 07 32 AM

I have not tested this on a real webhook, just a dead link, let me know if I need to test it on a real webhook, would be nice if there's an existing test endpoint for that. 
I have not added any tests on the frontend side, since I could only find e2e tests, please let me know if tests needed to be added on frontend for this change. 

NOTE: I found a lot of unrelated errors to my changes when running `npm run lint:fix`, I commited the changes related to my PR and ignored the rest, let me know what was the ideal approach here, same with pre-commit

### CODE REVIEW

File: frontend/web/components/TestWebhook.tsx [hunk 1]
```diff
@@ -8,18 +8,72 @@ import Button from './base/forms/Button'
...
+        })
+    })
+}
+
+const TestWebhook: FC<TestWebhookType> = ({ json, secret, webhook }) => {
   const [error, setError] = useState<string | null>(null)
   const [loading, setLoading] = useState(false)
   const [success, setSuccess] = useState(false)
+  const [sign, setSign] = useState('')
+  getSignature(json, secret, setSign)
```
Comment (kyle-ssg) [inline frontend/web/components/TestWebhook.tsx]: I think rather than re-evaluating this each render we may as well just do this on submit

File: frontend/web/components/TestWebhook.tsx [hunk 2]
```diff
@@ -8,18 +8,72 @@ import Button from './base/forms/Button'
...
+    'X-Flagsmith-Signature': sign,
+  }
+
   const submit = () => {
     setError(null)
     setLoading(true)
     setSuccess(false)
     data
-      .post(webhook, JSON.parse(json), null)
+      .post(webhook, JSON.parse(json), headers)
```
Comment (kyle-ssg) [inline frontend/web/components/TestWebhook.tsx]: RE above comment, this could be something more like 
```
getSignature().then((sign)=>{
 const headers = {
    'X-Flagsmith-Signature': sign,
  }
 return data.post(...)
}).then
```

File: frontend/web/components/TestWebhook.tsx (hunk 1 above)
Comment (shubham-padia) [reply frontend/web/components/TestWebhook.tsx]: Agreed! Fixed at https://github.com/Flagsmith/flagsmith/compare/446e37228ee813f6f6503e5d2b950850f3b593a6..39cc696750aa1916fe6376fc6babbae6676cac0b along with a bit of refactoring

File: frontend/web/components/TestWebhook.tsx (hunk 2 above)
Comment (shubham-padia) [reply frontend/web/components/TestWebhook.tsx]: Thanks for the review! Fixed at https://github.com/Flagsmith/flagsmith/compare/446e37228ee813f6f6503e5d2b950850f3b593a6..39cc696750aa1916fe6376fc6babbae6676cac0b along with a bit of refactoring

**Review by kyle-ssg — APPROVED** [review]
Great from a FE perspective, I'll handover to another member of the team from a backend perspective. Thank you very much for this!

**Comment by shubham-padia** [comment]
Bump for review

File: api/core/signing.py [hunk 3]
```diff
@@ -3,6 +3,8 @@
 
 
 def sign_payload(payload: str, key: str):
+    # TestWebHook on the frontend replicates this exact function, change the
+    # function there if this changes.
```
Comment (khvn26) [inline api/core/signing.py]: 1. For consistency's sake, let's call the frontend function `signPayload`.
2. I'd prefer to explicitly state the frontend module name in this here comment.

Comment (shubham-padia) [reply api/core/signing.py]: @khvn26 I've addressed the comments and the pushed the fix

File: api/webhooks/webhooks.py [hunk 4]
```diff
@@ -153,6 +153,8 @@ def _call_webhook(
     headers = {"content-type": "application/json"}
     json_data = json.dumps(data, sort_keys=True, cls=DjangoJSONEncoder)
     if webhook.secret:
+        # TestWebHook on the frontend replicates this exact function, change the
```
Comment (khvn26) [inline api/webhooks/webhooks.py]:
```suggestion
        # signPayload of frontend/web/components/TestWebHook on the frontend replicates this exact function, change the
```

File: api/webhooks/webhooks.py [hunk 5]
```diff
@@ -199,6 +201,8 @@ def call_webhook_with_failure_mail_after_retries(
...
```
Comment (khvn26) [inline api/webhooks/webhooks.py]:
```suggestion
        # signPayload of frontend/web/components/TestWebHook on the frontend replicates this exact function, change the
```

**Review by khvn26 — APPROVED** [review]

File: api/core/signing.py (hunk 3 above)
Comment (khvn26) [reply api/core/signing.py]: Great, thanks! I've replicated your change across the rest of the new code comments.

Comment (shubham-padia) [reply api/core/signing.py]: Missed that, thanks for replicating the changes!

**Comment by matthewelwell** [comment]
@shubham-padia @khvn26 looks like we've got CI failures here now, can we fix?

**Comment by shubham-padia** [comment]
> @shubham-padia @khvn26 looks like we've got CI failures here now, can we fix?

@kyle-ssg fixed!

**Comment by shubham-padia** [comment]
Just checking if there are any blockers to getting this merged :) !

File: api/edge_api/identities/edge_request_forwarder.py [hunk 6]
```diff
@@ -81,6 +81,9 @@ def _get_headers(request_method: str, headers: dict, payload: str = "") -> dict:
     # ref: https://groups.google.com/g/django-developers/c/xjYVJN-RguA/m/G9krDqawchQJ
     if request_method == "GET":
         headers.pop("Content-Length", None)
+
```
Comment (gagantrivedi) [inline api/edge_api/identities/edge_request_forwarder.py]: This comment should not be here; edge-forwarding is different from webhooks

**Review by gagantrivedi — CHANGES_REQUESTED** [review]

File: frontend/web/components/TestWebhook.tsx [hunk 7]
```diff
@@ -8,34 +8,82 @@ import Button from './base/forms/Button'
...
+  let result = JSON.stringify(obj, null, 1) // stringify, with line-breaks and indents
+  result = result.replace(/^ +/gm, ' ') // remove all but the first space for each line
+  result = result.replace(/\n/g, '') // remove line-breaks
+  result = result.replace(/{ /g, '{').replace(/ }/g, '}') // remove spaces between object-braces and first/last props
+  result = result.replace(/\[ /g, '[').replace(/ \]/g, ']') // remove spaces between array-brackets and first/last items
+  return result
+}
+
+const signPayload = async (body: string, secret: string): Promise<string> => {
+  if(!secret) {
```
Comment (kyle-ssg) [inline frontend/web/components/TestWebhook.tsx:26]: Just a note, added this as it was rejecting attempting to sign with an empty secret. Instead it just resolves with '' in this case.

**Review by gagantrivedi — APPROVED** [review]
