### PR TITLE
fix: user delete social auth

### LINKED ISSUE #2782: Allow deletion of accounts that don't have password
**Describe the bug**

Delete accounts asks for passwords, but accounts created using social auth don't have passwords

**To Reproduce**

1. Create an account using google or github
2. Try to delete that account

**Expected behavior**

Deletion should be allowed 

**Current workaround**

From the login page, follow the reset password workflow to generate a password which can subsequently be used to delete the account.

### PR DESCRIPTION
**Pull request by shubham-padia**
Fixes #2782 
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

We are enabling passwordless deletions only for Github and Google accounts and not for non email/password auth accounts, since it doesn't feel right to assume the behaviour of the next social auth that might be added. It's been a while since I dabbled with React, so please lmk if I should structure the code in a different way.

I'm also just ignoring the password field altogether for social auth as you can see in the API tests. Lmk if there are any concerns there. 

## How did you test this code?

Delete user with email/password:

https://github.com/Flagsmith/flagsmith/assets/13910561/ff5a9e1b-6257-49c5-853c-7879aa69cd34

Delete user with social auth (only tested on google for now):

https://github.com/Flagsmith/flagsmith/assets/13910561/cf3a44ad-0fe8-4da8-a4e3-7cd9bf660432

### CODE REVIEW

File: frontend/web/components/pages/AccountSettingsPage.js [hunk 1]
```diff
@@ -126,6 +128,7 @@ class TheComponent extends Component {
   render() {
     const {
       state: {
+        auth_type,
```
Comment (shubham-padia) [inline frontend/web/components/pages/AccountSettingsPage.js:131]: Using snake case here, since first_name, last_name and similar fields are also doing the same for fields fetched from the API

File: frontend/web/components/modals/ConfirmDeleteAccount.tsx [hunk 2]
```diff
@@ -10,13 +10,35 @@ import ErrorMessage from 'components/ErrorMessage'
...
+    ERROR_MESSAGES.default,
+  )
+  const [isEmailMismatchError, setIsEmailMismatchError] =
+    useState<boolean>(false)
+  const [
+    deleteUserAccount,
+    { isError: isMutationError, isSuccess: updateSuccess },
+  ] = useDeleteAccountMutation()
+  const skipPasswordConfirmation =
+    auth_type === 'GOOGLE' || auth_type === 'GITHUB'
```
Comment (shubham-padia) [inline frontend/web/components/modals/ConfirmDeleteAccount.tsx:41]: Using string literals here, since I could not find enums being used elsewhere in the frontend codebase

**Comment by shubham-padia** [comment]
> ## [Codecov](https://app.codecov.io/gh/Flagsmith/flagsmith/pull/3693?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Flagsmith) Report
> Attention: Patch coverage is `80.00000%` with `9 lines` in your changes are missing coverage. Please review.
> 
> > Project coverage is 95.86%. Comparing base [(`87d2d52`)](https://app.codecov.io/gh/Flagsmith/flagsmith/commit/87d2d52b21f161352b9880aaae210853ceb9e321?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Flagsmith) to head [(`0277681`)](https://app.codecov.io/gh/Flagsmith/flagsmith/pull/3693?dropdown=coverage&src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Flagsmith).
> > Report is 1 commits behind head on main.
> 
> [Files](https://app.codecov.io/gh/Flagsmith/flagsmith/pull/3693?dropdown=coverage&src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Flagsmith)	Patch %	Lines
> [api/custom_auth/serializers.py](https://app.codecov.io/gh/Flagsmith/flagsmith/pull/3693?src=pr&el=tree&filepath=api%2Fcustom_auth%2Fserializers.py&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Flagsmith#diff-YXBpL2N1c3RvbV9hdXRoL3NlcmlhbGl6ZXJzLnB5)	43.75%	[9 Missing ⚠️ ](https://app.codecov.io/gh/Flagsmith/flagsmith/pull/3693?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Flagsmith)
> Additional details and impacted files
> [☔ View full report in Codecov by Sentry](https://app.codecov.io/gh/Flagsmith/flagsmith/pull/3693?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Flagsmith). 📢 Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Flagsmith).

Not sure why all of these 9 lines of code are not being covered, they should be called by the testing functions 🤔 , except the fail message. I can add tests for the fail message, but not sure if it should be this PR or another one since it is related to the original PR introducing the delete user functionality.

https://app.codecov.io/gh/Flagsmith/flagsmith/commit/9bd0e3fba28f33d7c96b6d76c1fcf408e2474e78 (screenshot below)
Screenshot 2024-03-28 at 4 36 38 PM

**Comment by shubham-padia** [comment]
bump for review

File: frontend/web/components/modals/ConfirmDeleteAccount.tsx (hunk 2 above)
Comment (novakzaballa) [reply frontend/web/components/modals/ConfirmDeleteAccount.tsx:41]: Sounds good.

File: frontend/web/components/pages/AccountSettingsPage.js (hunk 1 above)
Comment (novakzaballa) [reply frontend/web/components/pages/AccountSettingsPage.js:131]: Ok

File: api/tests/unit/users/test_unit_users_views.py [hunk 3]
```diff
@@ -608,32 +608,37 @@ def test_group_admin_can_retrieve_group(
...
-        url = "/api/v1/auth/users/me/"
-        return client.delete(
-            url, data=json.dumps(data), content_type="application/json"
-        )
-
     # create a couple of users
     email1 = "test1@example.com"
     email2 = "test2@example.com"
     email3 = "test3@example.com"
+
```
Comment (novakzaballa) [inline api/tests/unit/users/test_unit_users_views.py]: Could you please remove any unnecessary line breaks from the code?

**Review by novakzaballa — APPROVED** [review]
Approved, with a minor comment

**Comment by shubham-padia** [comment]
@novakzaballa Replied to your comment. Let me know if there are any other blockers to getting this merged :) !

File: api/tests/unit/users/test_unit_users_views.py (hunk 3 above)
Comment (matthewelwell) [reply api/tests/unit/users/test_unit_users_views.py]: @shubham-padia are you able to resolve this and we can get this merged?

**Review by matthewelwell — APPROVED** [review]
