### PR TITLE
fix: Disable is_admin switcher in Organization API Keys

### LINKED ISSUE #3644: When creating an Organisation API key, Free plans should not show the roles toggle
image

The Free plan should always just create a full permission API key.

### PR DESCRIPTION
**Pull request by dougfabris**
Thanks for submitting a PR! Please check the boxes below:

- [ ] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

It proposes to disabled the "is admin" switcher in order to not display roles toggle for free plans

Closes #3644

## How did you test this code?

- Go to organization API Keys
- Create or edit an api key
- Is admin should be disabled for free plans

### CODE REVIEW

File: frontend/web/components/AdminAPIKeys.js [hunk 1]
```diff
@@ -213,6 +216,7 @@ export class CreateAPIKey extends PureComponent {
                       })
                     }}
                     checked={is_admin}
+                    disabled={isFreePlan && is_admin}
```
Comment (matthewelwell) [inline frontend/web/components/AdminAPIKeys.js]: I think the following is a slightly neater way of doing this, but I appreciate that this is internal pricing logic that isn't necessarily something I expect the open source community to know about. Since the use of non-admin keys is only really useful when RBAC is available, I think we can use the 'RBAC' permission. 

```suggestion
                    disabled={Utils.getPlansPermission('RBAC') && is_admin}
```

By doing this, I think we can then remove the `isFreePlan` const defined above.

**Review by matthewelwell — COMMENTED** [review]
Hi @dougfabris, thanks very much for this - it's a very good catch. 

I think we can also extend it to add a banner that shows it is only available in our paid plans, but we can handle that internally. For now, getting the switcher disabled would be important for our customers. 

I've added one suggested improvement, but I'd happily merge it and take on the improvement internally if needed.

File: frontend/web/components/AdminAPIKeys.js (hunk 1 above)
Comment (dougfabris) [reply frontend/web/components/AdminAPIKeys.js]: Hey @matthewelwell Nice to know about the plans permissions, thanks for reviewing it! 
I just changed a little bit to `!Utils.getPlansPermission('RBAC')` since the function will return if the plan has the permission

Comment (matthewelwell) [reply frontend/web/components/AdminAPIKeys.js]: Good catch adding the leading `!` too, instead of my suggestion!

**Review by matthewelwell — APPROVED** [review]
Great, thanks @dougfabris !
