### PR TITLE
fix: Manage members layout is broken

### LINKED ISSUE #3001: Manage members layout is broken
What I see:

image

What the designs show:

image

### PR DESCRIPTION
**Pull request by novakzaballa**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

- Manage members layout is fixed

Before:
Screen Shot 2023-11-28 at 14 53 43

Now:
Screen Shot 2023-11-28 at 14 45 48

## How did you test this code?

- Go to manage -> Members -> Members

### CODE REVIEW

File: frontend/web/components/pages/OrganisationSettingsPage.js [hunk 1]
```diff
@@ -26,7 +26,7 @@ import PageTitle from 'components/PageTitle'
 import { getStore } from 'common/store'
 import { getRoles } from 'common/services/useRole'
 
-const widths = [450, 150, 100]
+const widths = [450, 150, 100, 250, 235, 255]
```
Comment (matthewelwell) [inline frontend/web/components/pages/OrganisationSettingsPage.js]: I'd quite like to understand why we define these widths here rather than just directly in the style objects below. 

It also would make sense to my somewhat picky brain if these were ordered, either smallest to largest or largest to smallest, I'm not _that_ fussy!

**Comment by matthewelwell** [comment]
I have tested this via the preview and it looks good to me, but I've added a comment on the implementation.

File: frontend/web/components/pages/OrganisationSettingsPage.js (hunk 1 above)
Comment (novakzaballa) [reply frontend/web/components/pages/OrganisationSettingsPage.js]: It seems that initially this array was used to give sizes to the panelSearch component, as I worked on that component I added those values ​​to the array.

Re-ordered.

**Review by matthewelwell — APPROVED** [review]
