### PR TITLE
fix: Infinite loop 404 after leaving the organisation

### LINKED ISSUE #2955: App can get stuck in 404 loop after leaving an organisation
Steps to reproduce: 

1. At app.flagsmith.com log in as a user with access to organisations A & B and navigate to a project in Organisation B
2. In the django admin, remove access for that user to organisation B
3. At app.flagsmith.com, refresh the page

This should result in the application entering a refresh loop, displaying a 404 page each time. Seemingly the only way to resolve it is to clear cookies and log in again. 

The steps above show a way to replicate this using the Django admin console, however, it is something that I believe to be happening to other users as well so there are likely other steps to reproduce through app.flagsmith.com only.

### PR DESCRIPTION
**Pull request by novakzaballa**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

- Removed the item 'lastEnv' from AsyncStorage the user is no longer a member of the organization.

## How did you test this code?

1. At app.flagsmith.com log in as a user with access to organisations A & B and navigate to a project in Organisation B.
2. In the Django admin, remove access for that user to organisation B.
3. At app.flagsmith.com, refresh the page.
4. The app no longer enters an infinite loop.

### CODE REVIEW

File: frontend/web/components/pages/NotFoundErrorPage.js [hunk 1]
```diff
@@ -14,8 +14,8 @@ const ComingSoon = class extends Component {
         <h3 className='pt-5'>Oops!</h3>
         <p>
           It looks like you do not have permission to view this{' '}
-          {Utils.fromParam().entity || 'page'}. Please contact a member with
-          administrator privileges.
+          {Utils.fromParam().entity || 'page'} or you are not a member of the
+          organisation . Please contact a member with administrator privileges.
```
Comment (matthewelwell) [inline frontend/web/components/pages/NotFoundErrorPage.js]: I don't think this needs to change, I don't want to leak any extra data.

**Review by matthewelwell — CHANGES_REQUESTED** [review]
I've tested and confirmed this looks good. One minor comment related to the error message change.

**Review by matthewelwell — APPROVED** [review]
I reverted the error message change.
