### PR TITLE
fix: Show scheduled change request

### LINKED ISSUE #3005: The detail view for the scheduled feature changes does not show the upcoming value
**Describe the bug**

See below, the live value of the feature for the environment is listed, but the actual scheduled value is not listed.

image

**To Reproduce**

1. Schedule a change to a feature.
2. Click the `Scheduling` tab for a given environment.
3. Click on the scheduled feature change.
4. Observe that it is not visible. 

**Expected behavior**

The value of the upcoming change.

**How are you running Flagsmith?**

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [x] I work for Flagsmith

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes
- Scheduled change requests will now show the live and scheduled change
- Published change requests will now show the change request regardless whether it has been committed or not
- Committed change requests no longer have CTAs

## How did you test this code?

- View a closed change request
- Viewed a scheduled change

image

### CODE REVIEW

File: frontend/web/components/pages/ChangeRequestPage.js [hunk 1]
```diff
@@ -652,102 +650,97 @@ const ChangeRequestsPage = class extends Component {
...
+                                </Flex>
+                              </Row>
 
-                                {isMv &&
-                                  mvData.map((v, i) => (
-                                    <Row
-                                      key={i}
-                                      className='list-item px-4 align-start change-request-item'
+                              {isMv &&
+                                mvData.map((v, i) => (
```
Comment (zachaysan) [inline frontend/web/components/pages/ChangeRequestPage.js:701]: I understanding you're just dealing with existing code and changing the tabbing, but since it is involved with the PR I'll just mention that the name `isMv` and `mvData` and `map((v, i) => ...` make this section sorta hard to understand.

**Review by zachaysan — APPROVED** [review]
This looks like a small change that has a side effect of a larger diff. I didn't see any logical errors but I have one bit of feedback around the naming of one part.

File: frontend/web/components/pages/ChangeRequestPage.js (hunk 1 above)
Comment (kyle-ssg) [reply frontend/web/components/pages/ChangeRequestPage.js:701]: Sure, this is essentially showing differences in change request on multivariate flag variations.
