### PR TITLE
fix: subscription state

### LINKED ISSUE #3952: Navigation issues post plan change in organisation settings
When completing a change of plan in the organisation settings (note that this happens for upgrades and downgrades), the FE shows an error message regarding permissions and the navigation does not show all the options. 

https://www.loom.com/share/3f06d7304a7c477c86412b26349822be?sid=bf0245b7-e21e-4973-9de7-bb78bb934d41

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

Closes https://github.com/Flagsmith/flagsmith/issues/3952

Fixes state when subscription by refreshing the organisations.

## How did you test this code?

Subscribed on staging.

### CODE REVIEW

File: frontend/common/stores/account-store.js [hunk 1]
```diff
@@ -367,20 +367,15 @@ const controller = {
...
       )
       .then((res) => {
-        const idx = _.findIndex(store.model.organisations, {
-          id: store.organisation.id,
+        try {
+          if (res && res.subscription && res.subscription.plan) {
+            API.trackEvent(Constants.events.UPGRADE(res.subscription.plan))
+            API.postEvent(res.subscription.plan, 'chargebee')
+          }
+        } catch (e) {}
```
Comment (zachaysan) [inline frontend/common/stores/account-store.js:375]: I don't really love the empty catch here. Can we silently swallow error conditions that we've allowlisted ahead of time?

**Review by zachaysan — APPROVED** [review]
Provisionally approved with one improvement suggested.

File: frontend/common/stores/account-store.js (hunk 1 above)
Comment (kyle-ssg) [reply frontend/common/stores/account-store.js:375]: This is just in case Analytics tools are broke for whatever reason, in which case we'd still see something in sentry. Just needs to ensure the later more important things happen regardless.
