### PR TITLE
fix first creation of segment in self-hosted context

### LINKED ISSUE #1354: Cannot create a segment on self-hosted
Hello!
I started to play a bit with Flagsmith. It really feels good and the documentation is super clear. Great job!
I just have an issue when I try to create my first segment after running the docker compose (so the steps to reproduce are only to dl [the docker image](https://docs.flagsmith.com/deployment/docker) and run `docker-compose up`)

Screenshot 2022-08-05 at 14 05 54

Did I do something wrong?
If this is indeed a bug, I can probably have a look and open a PR if you're already overwhelmed
Thanks!

### PR DESCRIPTION
**Pull request by PrettyWood**
When starting a brand new instance of flagsmith in self-hosted environment, I couldn't create a segment. This is because I didn't set the `segment_operators` remote config value.
But this was not explained directly in the product. This is a proposition to fix this behavior

closes #1354

### BEFORE
Screenshot 2022-08-18 at 14 56 43

### AFTER
Screenshot 2022-08-18 at 15 32 46

### CODE REVIEW

File: frontend/web/components/pages/SegmentsPage.js [hunk 1]
```diff
@@ -1,8 +1,15 @@
 import React, { Component } from 'react';
 import CreateSegmentModal from '../modals/CreateSegment';
-import TryIt from '../TryIt';
```
Comment (PrettyWood) [inline frontend/web/components/pages/SegmentsPage.js:3]: unused import

**Comment by kyle-ssg** [comment]
Ah this is a great quality of life change, thanks so much @PrettyWood
