### PR TITLE
fix: permanent tag icons

### LINKED ISSUE #4794: Only permanent tags should show the lock icon
Currently all tags are displayed with the lock icon. This icon should only be shown on tags configured as permanent. 

Image
Image

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

Removes lock icon from non-permanent tags 

## How did you test this code?

_Please describe._

### CODE REVIEW

File: frontend/web/components/tags/TagContent.tsx [hunk 1]
```diff
@@ -20,7 +20,13 @@ function escapeHTML(unsafe: string) {
...
 }
 
-const renderIcon = (tagType: string, tagColor: string, tagLabel: string) => {
+const renderIcon = (
+  tagType: string,
+  tagColor: string,
+  tagLabel: string,
+  isPermanent: boolean,
+) => {
+  console.log(tagType, tagLabel)
```
Comment (matthewelwell) [inline frontend/web/components/tags/TagContent.tsx]: Do we need this console log?

**Review by matthewelwell — APPROVED** [review]
Approved with a minor comment
