### PR TITLE
fix: async feature versioning test

### LINKED ISSUE #3712: Locally and sometimes in the e2e tests, the value of use_v2_feature_versioning does not update from false to true when you enable this feature.
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [X] Some other way (add details in description below)

### Describe the bug

The versioning e2e test may fail because the hideHistory value, which depends on whether `use_v2_feature_versioning` is enabled, is `false`.

Locally, if you create a new project and enable the Feature versioning function without any flags, the value does not change.

### Steps To Reproduce

In the e2e test:
- Run the e2e versioning test
Local:
- Create a new Organisation and a new project
- Go to the setting from an environment
- Enable Feature Versioning -> Confirm the modal
- Refresh the page
- The Feature Versioning switch is disabled, and the API response indicates that the value of `use_v2_feature_versioning` is false.

### Expected behavior

If you enabled the Feature Versioning switch and the modal is confirmed, the `use_v2_feature_versioning` would be changed to true.

### Screenshots

https://github.com/Flagsmith/flagsmith/assets/41410593/7af09141-721b-4953-8a6f-fea6c1652ea5

In the Versioning test:

Screen Shot 2024-04-02 at 18 40 38

### PR DESCRIPTION
**Pull request by kyle-ssg**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

We had intermittent failures in the versioning test, there are 2 reasons why this would happen

- The action to enable an environment versioning is async, it could take a while to process
- The frontend was incorrectly saving the environment when the feature was enabled

### CODE REVIEW

**Review by novakzaballa — APPROVED** [review]
LGTM, but some test are now failing.

File: frontend/web/components/pages/EnvironmentSettingsPage.js [hunk 1]
```diff
@@ -115,32 +115,10 @@ const EnvironmentSettingsPage = class extends Component {
...
-        hide_sensitive_data: !!this.state.hide_sensitive_data,
-        minimum_change_request_approvals: has4EyesPermission
-          ? this.state.minimum_change_request_approvals
-          : null,
-        name: name || env.name,
-        use_identity_composite_key_for_hashing:
-          !!this.state.use_identity_composite_key_for_hashing,
-        use_mv_v2_evaluation: !!this.state.use_mv_v2_evaluation,
-      }),
-    )
```
Comment (novakzaballa) [inline frontend/web/components/pages/EnvironmentSettingsPage.js:143]: It looks like removing these lines breakes the ability to update the environment name.
image

**Review by novakzaballa — CHANGES_REQUESTED** [review]

**Review by novakzaballa — APPROVED** [review]
LGTM
